---
- hosts: ansible-awx
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
      loop:
        - vim
        - curl
        - unzip
        - atop
        - bmon
        - iotop
        - net-tools
        - nfs-common
        - ntpdate
        - qemu-guest-agent
        - snmpd
        - zabbix-agent
    - name: Set timezone to US/Detroit
      timezone:
        name: America/Detroit
